[project]
name = "reasyn"
version = "0.1.0"
description = "ReaSyn code"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [
    { name = "NVIDIA corp" },
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "click==8.2.1",
    "datasets==4.0.0",
    "editdistance==0.8.1",
    "einops",
    "joblib",
    "numpy==1.26.4",
    "omegaconf==2.3.0",
    "pandas==2.3.1",
    "pytdc==0.4.1",
    "pytorch-lightning==2.5.3",
    "pyyaml==6.0.2",
    "rdkit==2025.3.2",
    "rotary-embedding-torch>=0.9.1",
    "scikit-learn==1.2.2",
    "setuptools>=65,<82",
    "synformer>=0.1.3",
    "torch==2.7.0",
    "torchtyping==0.1.5",
    "tqdm==4.67.1",
    "transformers==4.53.2",
    "wandb==0.19.11",
]

[dependency-groups]
dev = [
    "black",
    "flake8",
    "isort",
    "mypy==1.15.0",
    "pre-commit",
    "pytest",
    "rich",
    "sphinx",
    "sphinx-rtd-theme",
    "types-pyyaml",
]

[build-system]
requires = ["hatchling>=1,<2"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["reasyn"]
